# -*- coding: utf-8 -*-
"""Week 2 Homework.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1go-lTQdXFtLRYZji8eXV9BU45uFCeuWV

# **Simulation model for 1 ice cream server, 1 queue of customers scenario**

**Pseudocode**

for time t within period P:

     randomly determines whether a new customer C0 arrives

     if True:           
           add C0 to queue Q
     if server is not busy:
           C1 = Q.pop()
           randomly set service time S for C1   
           set server.busy to True
     else:
            S = S - 1
            if S == 0:
               set server.busy = False
"""

import random
Q = []
for t in range(10):
  num = random.randint(1,10)
  Q.append(num) #The append() method in python adds a single item to the existing list. 
                #It doesn’t return a new list of items but will modify the original list 
                #by adding the item to the end of the list.

simPeriod = 100
serverBusy = False #boolean false
currentService=0
qSize = [] #empty list
for t in range(simPeriod):
  print('At time: ', t)
  if not serverBusy and len(Q)>0: # len returns the length of string or data
          currentService=Q.pop() #number between the range of 1-10 will be popped out
          print(" Next customer is being served,with service time=", currentService)
          serverBusy = True
  elif serverBusy and len(Q)>=0:
        currentService=currentService-1
        print('Server currently busy. Time left: ', currentService, ' minutes')
        if currentService == 0:
          serverBusy = False
  elif len(Q) <= 0:
        print('Server is not Busy.')
  qSize.append(len(Q))